### ISSUE TITLE
Wildcard subdomains and dnsmasq on a local machine

### ISSUE THREAD

**Issue by ad-on-is** [dprandzioch/docker-ddns#20]
As of now, the API allows the configuration of subdomains, i.e. `foo.dyndns.domain.tld` or `bar.foo.dyndns.domain.tld`.

Is it possible to configure a wildcard subdomain, like `*.foo.dyndns.domain.tld` and have a `dnsmasq` running on a local machine, which handles all the rest?

**Comment by dstapp** [comment]
So given you have a upstream server with a static IP that runs this project (as you need one server with a static IP that will act as the DDNS nameserver), you would like docker-ddns to create a NS record (instead of an A record) that delegates to your local machine running dnsmasq?

Currently docker-ddns is only capable to create A/AAAA records, which will not allow the described use-case with zone delegation to work.
Wildcard subdomains are possible (or at least not filtered, so should work), but this will only redirect all subdomains of `foo.dyndns.domain.tld` of your example to a specific IP address (e.g. your local machine), which could than expose services on this by vhosts in nginx or whatever.

If you really want true zone delegation though to have another DNS server running which has a dynamic IP address itself only (which I don't consider a good idea), I would need to extend the list of possible RR types to include `NS` records, but I really would try to avoid that to be honest.

However, please let me know if the first suggested case will work for you.

**Comment by ad-on-is** [comment]
With some trial and error I achived what I was looking for:

`http://ns.domain.tld:8080/update?secret=xxx&domain=*.office&addr=123.45.67.89` seems to be the way to go.

This creates an A-record like this:

    $ORIGIN office.dyndns.domain.tld.
    $TTL 3600	; 1 hour
    *			A	123.45.67.89


Now, from outside of my LAN a call to `project1.dev1.office.dyndns.domain.tld` points to my public IP-address. I verified it working with `https://www.whatsmydns.net/#A/what.so.ever.office.dyndns.domain.tld`

In my routers dnsmasq-config-file I've configured, that all requests point to a specific local IP based on the subdomain.

something like:

    address=/dev1.office.dyndns.domain.tld/192.168.1.10
    address=/dev2.office.dyndns.domain.tld/192.168.1.20

Additionally, in my routers firewall-settings I've set a port-forwarding from outside to inside like this:

`dev1.office.dyndns.domain.tld:8010` points to `192.168.1.10:80`
`dev1.office.dyndns.domain.tld:8020` points to `192.168.1.20:80`

I think there's no further work necessary here.

**Comment by ad-on-is** [comment]
> you would like docker-ddns to create a NS record (instead of an A record) that delegates to your local machine

As far as I understand DNS, in this case, it should be a CNAME-record, not an NS-record... but as it turns out, an A-record does the job too.

**Comment by dstapp** [comment]
I'll close this issue since there's nothing left to do. If you have any further problems, please file a new bug.
