### ISSUE TITLE
Alpine docker, domain updates for x-hosts, SmartDNS, port change

### ISSUE THREAD

**Issue by atharmian** [dprandzioch/docker-ddns#25]
Hi from Toronto !

Exactly what I was looking for...just read the article.

Newbie here so bear with me 👺👺👺

1. Can this be run in an Alpine base Docker, x86 or aarch64?

How would a router with hosts behind connect to the Docker dynDNS server?

2. How many hosts behind multiple routers in different homes can this support?

Are domain hoster mymachine.dyndns.mydomain.net updates for adding each host machine automatic?
Can updates be automated?

3. If I want to use SmartDNS Proxy services (for multiple sites geo unlocking without encryption for good speeds) with this DIY dynDNS , how would I ?

Do I just have to use DNS addresses provided by SmartDNS Proxy provider plugged into my home router?

4. On above note, any links to DIY SmartDNS Proxy server, possibly a combo DIY dynDNS+ SmartDNS Proxy server?

5. As you know the standard port 53 is prone to ISP DNS hijacking, so many external DNS providers recommend you change the port to say 54 in your router configuration.

Can we do the port change here?

**Comment by dstapp** [comment]
Hey there,

1. the official image that I provide on DockerHub runs in a Debian Stretch container x86_64, I've had plans to port it to Alpine, but there's nothing done yet, feel free to open a PR ;-)

2. I'm not sure if I understand the questions below. This project aims to provide a DDNS server, which you can self-host, similar to dyndns.org. Thus, you'll need an external server e.g. some cheap VPS to host this project on, and you need an upstream DNS provider, which a domain set up. It works that way, that you'll redirect a zone from your domain, e.g. dyndns.example.com to the DDNS server on your VPS, so that any DNS requests to that zone are delegated to the DDNS server on your VPS. Alongside the DDNS server this project provides an API which allows to update DNS records using HTTP requests, see `README.md`. Thus, you can update it automatically e.g. by creating a cronjob on a machine in your local network or use your routers DynDNS support if this supports custom providers.

So to the question: It supports any amount of different homes you have, the hosts behind your router (given your router provides a single IP address to the outside world and uses NAT to forward to local devices) have to be exposed as usual by port-mappings or service-specific dispatching like vhosts on webservers.

3+4. I don't know what SmartDNS is, sorry :-) Googling it seems that it serves a different purpose than what this project aims at, which is primarily making devices on your local network accessible from the outside world.

5. Since you don't host the DNS on your local network anyway but with any external hoster, this should not be a problem. If you would host this at home, there'd be no point of using this approach at all since the IPs provided by your ISP are probably dynamic and therefore not suitable for running DNS services, or the other way around, if your ISP provides you with a static IP, but then what would you need DDNS for?

I hope this helps you somehow, if you have any further questions, just shoot me a message.

**Comment by dstapp** [comment]
I'll close this issue since there's nothing left to do. If you have any further problems, please file a new bug.
