### ISSUE TITLE
subdomain of  mydomain can't work

### ISSUE THREAD

**Issue by haoglehaogle** [dprandzioch/docker-ddns#26]
hello,
It can work well, if use subdomain of subdomain of  mydomain. such as: xxx.ddns.mydomain.com
in envfile,
ZONE=dyndns.mydomain.com

I chage envfile in it:
ZONE=mydomain.com
and I want to use subdomain of mydomain, xxx.mydomain.com, but It don't work.

Can this docker support subdomain of mydomain?

**Comment by dstapp** [comment]
Hey, that's an interesting problem.

The problem is that you need to specify a zone which is handled by docker-ddns. Of course, you can also set the DNS server for mydomain.com to your docker-ddns installation, then you'll be able to do something like mypc.mydomain.com, but then mydomain.com would be exclusively reserved for DDNS clients, which you probably don't want, right?

Another option would be to set up docker-ddns like described in the README using ZONE=xxx.mydomain.com and then create a DNS record for "@", which would be the zone root, so "xxx.mydomain.com" itself. But that way you can only have one DDNS client and I'm not sure the API and nsupdate allow to do something like this. Feel free to test it and let me know :)

**Comment by dstapp** [comment]
Closed due to inactivity.
