### ISSUE TITLE
DNS Setup

### ISSUE THREAD

**Issue by DaveDischord** [dprandzioch/docker-ddns#6]
I can see that a couple people have [had] the same issue as I did starting, but with no clear resolution typed out. I've set up everything as per how-to. 
I'm using GoDaddy as a hosting site for [myDomain.net], and have exported my DNS records. The ones in question look like this:
; A Records
ns	3600	IN	A	<ip address="" of="" server="">
; NS Records
dyndns	3600	IN	NS	ns

the envfile:
ZONE=myDomain.net

In the browser:
http://ns.myDomain.net:8080...
returns
{"Success":true,"Message":"Updated A record for googleTest to IP address 216.58.194.78"}

however,
In the browser
http://googletest.dyndns.my...
returns 
This site can’t be reached
googletest.dyndns.myDomain.net’s server DNS address could not be found.

What am I missing and thank you for your time.

**Comment by dstapp** [comment]
Aah I think I know the problem :-) And I agree that the example in the documentation is misleading here. 

You configured a NS record for `dyndns.myDomain.net`, right? So your `ZONE` variable in the `envfile` has to be like this: 

`ZONE=dyndns.myDomain.net`

and when you send a DDNS request to the REST API then (in your example `googleTest`) this will be be the domain `googleTest.dyndns.myDomain.net` in the end. So the important thing here is to set `ZONE` properly according to your `dyndns` NS record. Please remove the docker container after changing the envfile and create it from scratch as I'm not sure right know if this is written to some configuration file that is then stored within the container instance. 

Can you please try that and give me some feedback if this worked for you?

**Comment by DaveDischord** [comment]
OK.  I've edited and rebuilt, but still no luck.  
http://ns.sugarwitch.net:8080/update?secret=_Secret_&domain=webTest&addr=_IPaddr_
Returns -> {"Success":true,"Message":"Updated A record for webTest to IP address _IPaddr_"}
Brought up the log:

- sudo docker logs -f dyndns
- creating
- zone...
- creating
- zone file...
- creating REST api config...
- [ ok ] Starting domain name service...: bind9.
- 2017/09/06 13:05:49 Serving dyndns REST services on 0.0.0.0:8080...
- 2017/09/06 13:41:28 A record update request: webTest -> _IPaddr_

webtest.dyndns.sugarwitch.net -> DNS address could not be found.
I know its probably something silly, but its just not clear to me.

**Comment by dstapp** [comment]
Did you create a "NS" record for dyndns.sugarwitch.net pointing to the same address as the "A" record for ns.sugarwitch.net ? (I believe this should be 63.96.9.170). Because when I run 

`dig NS dyndns.sugarwitch.net`

I get no record back for your "dyndns" domain:

```
; <<>> DiG 9.9.7-P3 <<>> NS dyndns.sugarwitch.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 34135
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dyndns.sugarwitch.net.		IN	NS

;; Query time: 23 msec
;; SERVER: 192.168.0.20#53(192.168.0.20)
;; WHEN: Wed Sep 06 18:56:21 CEST 2017
;; MSG SIZE  rcvd: 50
```

It returns with `SERVFAIL` which means that the requested zone does not exist on the nameserver that provides your domain.

Here's my DNS records that work for me:

```
$TTL 3600
[...]
dyndns     IN NS      ns
@              IN NS      [blabla].

ns             IN A       [my server ip]
```

The answer section for my NS lookup looks like this

```
thirteen:~() $ dig NS dyndns.[foo] @8.8.8.8

; <<>> DiG 9.9.7-P3 <<>> NS dyndns.[foo] @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16240
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;dyn.dyndns.[foo].			IN	NS

;; ANSWER SECTION:
dyn.dyndns.[foo].		86399	IN	NS	localhost.

;; Query time: 62 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Sep 06 19:09:56 CEST 2017
;; MSG SIZE  rcvd: 63
```

As you can see, it returns status `NOERROR` which means that the zone exists on the nameserver (although I have no clue why it returns localhost in the answer section, maybe this is something regarding policies / maybe someone else has more insight here). 

I'd guess your problem lays somehow there. Maybe NS delegation works different in the software GoDaddy is using, I'm not sure which one this is.

Maybe this helps? https://networkhobo.com/2014/07/22/godaddy-delegate-subdomain-to-different-nameserver/ This is essentially what I'm doing directly in my bind zonefile. Be sure to have the "host" fields exactly in the same format as described, I know that this can cause problems in different DNS implementations.

**Comment by DaveDischord** [comment]
I think I've found the culprit and am on the right track, I hope.  '53' wasn't opened up on my firewall.

**Comment by DaveDischord** [comment]
Now that its working, where can I find the list of pointers, in order to delete unused ones?

**Comment by dstapp** [comment]
OK, I'm happy that you were able to solve it! I'll close this one. If you have any further problems, just let me know.
